public with sharing class HelloWorld {
    public static void debugMethod(){
        System.debug('Hello World');
    }

    public integer add(integer a, integer b){
        return a+b;
    }

    public integer subtract(integer a, integer b){
        return a-b;
    }

    public integer div(integer a, integer b){
        return a/b;
    }
}                                                                                                                   